server:
  port: 10843
  servlet:
    context-path: "/game-service"

spring:
  datasource:
    ## local connection
    url: jdbc:mysql://localhost:3306/game?useSSL=true&enabledTLSProtocol=TLSv1.2
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  kafka:
    bootstrap-servers: localhost:9092
    group-id: group-1
    security-protocol-config: plaintext